package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import model.Hackathon;
import model.Partecipante;
import model.Utente;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static utils.Utils.*;


public class HackathonCreatiOrganizzatore {
    private JPanel panel1; // proviamo a inizializzarlo
    private JTable table1;
    private JButton dettaglioButton;
    private JButton tornaAllaHomeButton;
    public JFrame listaHackathonCFrame;
    public JFrame homeUtenteFrame;
    public DefaultTableModel listaHackathonCModel;
    private Controller controller;
    private ActionButton actionButton;
    public JFrame hcoFrame;

    public HackathonCreatiOrganizzatore(JFrame homeUtenteFrame, Controller controller) {
        this.homeUtenteFrame = homeUtenteFrame;
        this.controller = controller;
        this.actionButton = controller.getActionButton();
        this.dettaglioButton.setText(controller.getNomeButton());

        this.hcoFrame = new JFrame("HackathonCreatiOrganizzatore");
        hcoFrame.setContentPane(panel1); //hcoFrame invece di listaHackathonCFrame
        hcoFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        hcoFrame.pack();

        List<Hackathon> listaHackathon = null;
        try {
            listaHackathon = getMockHackathon(controller.getUtente());
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        Object[][] datiTable = new Object[listaHackathon.size()][4];

        for (int i = 0; i < listaHackathon.size(); i++) {
            datiTable[i][0] = listaHackathon.get(i).getId();
            datiTable[i][1] = listaHackathon.get(i).getNome();
            datiTable[i][2] = listaHackathon.get(i).getDescrizione();
        }


        DefaultTableModel tabellaHackathon = new DefaultTableModel(datiTable, COLONNE_LISTA_HACKATHON) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 -> Long.class;
                    default -> String.class;
                };
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        tornaAllaHomeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                homeUtenteFrame.setVisible(true);
                hcoFrame.setVisible(false);
                hcoFrame.dispose();
            }
        });

        dettaglioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    int riga = table1.getSelectedRow();
                    if (riga == -1) {
                        JOptionPane.showMessageDialog(panel1, "Seleziona un hackathon");
                        return;
                    }
                    Long id = Long.parseLong(table1.getValueAt(riga, 0).toString());
                    controller.setIdHackathon(id);
                    actionButton.doAction();
                    hcoFrame.setVisible(false);
                    hcoFrame.dispose();
                }catch (Exception ex){
                    throw new RuntimeException(ex);
                }

            }
        });
        table1.setModel(tabellaHackathon);
    }


    private List<Hackathon> getMockHackathon(Utente user) throws SQLException {
        String userType = getTipo(user);
        switch (userType) {
            case TIPO_ORGANIZZATORE:
                return controller.vediHackathonCreati(user);
            case TIPO_PARTECIPANTE:
                if (dettaglioButton.getText().equals("Iscriviti")) {
                    return controller.getHackathonLiberi((Partecipante) user);
                }
                return controller.getHackathonPartecipante((Partecipante) user);
            default:
                break;

        }

        Hackathon hackathon1 = new Hackathon();
        hackathon1.setId(1L);
        hackathon1.setNome("Hackathon1");
        hackathon1.setDescrizione("Questo è Hackathon1");

        Hackathon hackathon2 = new Hackathon();
        hackathon2.setId(2L);
        hackathon2.setNome("Hackathon2");
        hackathon2.setDescrizione("Questo è Hackathon2");

        List<Hackathon> listaHackathon = new ArrayList<>();
        listaHackathon.add(hackathon1);
        listaHackathon.add(hackathon2);
        return listaHackathon;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Lista Hackathon");
        panel1.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        table1 = new JTable();
        JScrollPane scrollPane = new JScrollPane(table1);
        panel2.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        dettaglioButton = new JButton();
        panel1.add(dettaglioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tornaAllaHomeButton = new JButton();
        tornaAllaHomeButton.setText("Torna alla Home");
        panel1.add(tornaAllaHomeButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

    }
}
