package gui;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class HomeOrganizzatore {
    private JPanel panel1;
    private JButton creaButton;
    private JButton vediButton;
    private JButton classificaButton;
    public JFrame homeOrganizzatoreFrame;
    private Controller controller;

    public HomeOrganizzatore(Controller controller) {
        this.controller = controller; //invece di controller=new Controller();
        this.homeOrganizzatoreFrame = new JFrame("HomeOrganizzatore");
        homeOrganizzatoreFrame.setContentPane(panel1);
        homeOrganizzatoreFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        homeOrganizzatoreFrame.pack();
        homeOrganizzatoreFrame.setVisible(true); //appena aggiunta
        vediButton.addActionListener(new ActionListener() {
            final ActionButton actionButton = new ActionButton() {
                @Override
                public void doAction() {
                    HackathonCreatiOrganizzatore hco = new HackathonCreatiOrganizzatore(homeOrganizzatoreFrame, controller);
                    DettagliHackathon dettagliHackathon = new DettagliHackathon(controller, hco.hcoFrame);
                    dettagliHackathon.dettaglioFrame.setVisible(true);
                }
            };

            @Override
            public void actionPerformed(ActionEvent e) {
                controller.setActionButton(actionButton);
                controller.setNomeButton("Vedi dettaglio");
                HackathonCreatiOrganizzatore hco = new HackathonCreatiOrganizzatore(homeOrganizzatoreFrame, controller);
                hco.hcoFrame.setVisible(true);
                homeOrganizzatoreFrame.setVisible(false);
            }
        });
        creaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CreaHackathon creaHackathon = new CreaHackathon(controller, homeOrganizzatoreFrame);
                creaHackathon.creaFrame.setVisible(true);
                homeOrganizzatoreFrame.setVisible(false);
            }
        });

        classificaButton.addActionListener(new ActionListener() {


            final ActionButton actionButton = new ActionButton() {
                @Override
                public void doAction() {
                    Classifica classifica = new Classifica(homeOrganizzatoreFrame, controller);
                    classifica.classificaFrame.setVisible(true);
                    homeOrganizzatoreFrame.setVisible(false);
                }
            };

            @Override
            public void actionPerformed(ActionEvent e) {
                controller.setNomeButton("Vedi classifica");
                controller.setActionButton(actionButton);
                HackathonCreatiOrganizzatore hackathonCreatiOrganizzatore = new HackathonCreatiOrganizzatore(homeOrganizzatoreFrame, controller);
                hackathonCreatiOrganizzatore.hcoFrame.setVisible(true);
                homeOrganizzatoreFrame.setVisible(false);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("ORGANIZZATORE");
        panel1.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("crea nuovo Hackathon:");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("vedi Hackathon creati:");
        panel1.add(label3, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        creaButton = new JButton();
        creaButton.setText("crea +");
        panel1.add(creaButton, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        vediButton = new JButton();
        vediButton.setText("vedi");
        panel1.add(vediButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        classificaButton = new JButton();
        classificaButton.setText("Classifica");
        panel2.add(classificaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
