package main.java.gui;

import main.java.controller.Controller;
import main.java.model.Team;
import main.java.model.Partecipante;
import main.java.model.Team;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static main.java.utils.Utils.*;

public class InviaRichiestaPartecipante {
    private JPanel panel1;
    private JTable table1;
    public JFrame inviaRichiestaPartecipanteFrame;
    public JFrame mittenteFrame;
    private Controller controller;
    private JButton inviaRichiestaButton;
    private JButton tornaIndietroButton;
    private ActionButton actionButton;



    public InviaRichiestaPartecipante(JFrame mittenteFrame, Controller controller) {

        this.mittenteFrame = mittenteFrame;
        this.inviaRichiestaPartecipanteFrame = new JFrame("InviaRichiestaPartecipante");
        this.controller = controller;
        inviaRichiestaPartecipanteFrame.setContentPane(panel1);
        inviaRichiestaPartecipanteFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        inviaRichiestaPartecipanteFrame.pack();
        this.actionButton = controller.getActionButton();
        this.inviaRichiestaButton.setText(controller.getNomeButton());

        List<Team> listaTeam = getMockTeam();

        Object[][] datiTable = new Object[listaTeam.size()][4];

        for (int i = 0; i < listaTeam.size(); i++) {
            datiTable[i][0] = listaTeam.get(i).getId();
            datiTable[i][1] = listaTeam.get(i).getNome();
        }


        DefaultTableModel tabellaTeam = new DefaultTableModel(datiTable, COLONNE_LISTA_TEAM) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 -> Long.class;
                    default -> String.class;
                };
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        inviaRichiestaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int rigaSelezionata = table1.getSelectedRow();
                if (rigaSelezionata < 0) {
                    JOptionPane.showMessageDialog(panel1, "Seleziona un Team");
                    return;
                }
                Long idTeam = (Long) table1.getValueAt(rigaSelezionata, 0);
                controller.setIdTeam(idTeam);

                if(inviaRichiestaButton.getText().equals("Invia richiesta")) {
                    inviaRichiestaIngressoTeam(idTeam,listaTeam);
                }

                actionButton.doAction();
                inviaRichiestaPartecipanteFrame.setVisible(false);
                inviaRichiestaPartecipanteFrame.dispose();

            }
        });

        tornaIndietroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mittenteFrame.setVisible(true);
                inviaRichiestaPartecipanteFrame.setVisible(false);
                inviaRichiestaPartecipanteFrame.dispose();


            }
        });

        table1.setModel(tabellaTeam);
        table1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


    }

    private void inviaRichiestaIngressoTeam(Long idTeam, List<Team> listaTeam){
        Optional<Team> teamRichiesto = listaTeam.stream()
                .filter(Team -> Team.getId().equals(idTeam))
                .findFirst();

        this.actionButton = new ActionButton() {
            @Override
            public void doAction() {
                controller.richiestaIngressoTeam((Partecipante) controller.getUtente(),teamRichiesto.get());
                JOptionPane.showMessageDialog(panel1, "Richiesta d'ingresso inviata");
            }
        };

    }

    private List<Team> getMockTeam() {
        Team Team1 = new Team("team1");
        Team1.setId(1L);

        Team Team2 = new Team("team2");
        Team2.setId(2L);

        List<Team> listaTeam = new ArrayList<>();
        listaTeam.add(Team1);
        listaTeam.add(Team2);
        return listaTeam;

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("INVIA RICHIESTA DI ACCESSO A UN TEAM");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        table1 = new JTable();
        JScrollPane scrollPane = new JScrollPane(table1);
        panel2.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        inviaRichiestaButton = new JButton();
        inviaRichiestaButton.setText("Invia richiesta");
        panel1.add(inviaRichiestaButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tornaIndietroButton = new JButton();
        tornaIndietroButton.setText("Torna indietro");
        panel2.add(tornaIndietroButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
