package gui;


import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import model.Giudice;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static utils.Utils.COLONNE_LISTA_PARTECIPANTI;


public class ListaGiudici {
    private JPanel panel1;
    private JTable table1;
    private JButton invitaButton;
    private JButton tornaAllaHomeButton;
    public JFrame listaGiudiciFrame;
    public JFrame mittenteFrame;
    public DefaultTableModel listaGiudiciModel;
    private Controller controller;


    public ListaGiudici(JFrame mittenteFrame, Controller controller) {

        this.mittenteFrame = mittenteFrame;
        this.listaGiudiciFrame = new JFrame("ListaGiudici");
        this.controller = controller;

        listaGiudiciFrame.setContentPane(panel1);
        listaGiudiciFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        listaGiudiciFrame.pack();

        List<Giudice> listaGiudici = controller.getListGiudici();
        String nomeTeam = controller.getNomeTeam();

        Object[][] datiTable = new Object[listaGiudici.size()][4];

        for (int i = 0; i < listaGiudici.size(); i++) {
            datiTable[i][0] = false;
            datiTable[i][1] = listaGiudici.get(i).getId();
            datiTable[i][2] = listaGiudici.get(i).getNome();
            datiTable[i][3] = listaGiudici.get(i).getCognome();
        }


        DefaultTableModel tabellaGiudici = new DefaultTableModel(datiTable, COLONNE_LISTA_PARTECIPANTI) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 -> Boolean.class;
                    case 1 -> Long.class;
                    default -> String.class;
                };
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return columnIndex == 0;
            }
        };
        this.listaGiudiciModel = tabellaGiudici;
        table1.setModel(tabellaGiudici);

        invitaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<Giudice> giudiciChecked = getCheckedGiudici(tabellaGiudici, listaGiudici);
                if (giudiciChecked.isEmpty()) {
                    JOptionPane.showMessageDialog(panel1, "Seleziona un giudice da invitare");
                    return;
                }
                controller.invitaGiudice(controller.getIdHackathon(), giudiciChecked);
                JOptionPane.showMessageDialog(panel1, "Invito inviato con successo");
                mittenteFrame.setVisible(true);
                listaGiudiciFrame.setVisible(false);
                listaGiudiciFrame.dispose();
            }
        });

        tornaAllaHomeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mittenteFrame.setVisible(true);
                listaGiudiciFrame.setVisible(false);
                listaGiudiciFrame.dispose();
            }
        });

    }

    private List<Giudice> getCheckedGiudici(DefaultTableModel tabellaGiudici, List<Giudice> listaGiudici) {
        List<Giudice> GiudiciChecked = new ArrayList<>();
        for (int i = 0; i < listaGiudici.size(); i++) {
            Boolean check = (Boolean) tabellaGiudici.getValueAt(i, 0);

            if (Boolean.TRUE.equals(check)) {
                Long id = (Long) tabellaGiudici.getValueAt(i, 1);
                Giudice Giudicechecked = listaGiudici.stream()
                        .filter(Giudice -> Giudice.getId().equals(id))
                        .findFirst().orElse(null);
                GiudiciChecked.add(Giudicechecked);
            }
        }

        return GiudiciChecked;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("LISTA Giudici DA INVITARE");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        table1 = new JTable();
        JScrollPane scrollPane = new JScrollPane(table1);
        panel2.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        invitaButton = new JButton();
        invitaButton.setText("Invita");
        panel1.add(invitaButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tornaAllaHomeButton = new JButton();
        tornaAllaHomeButton.setText("torna alla home");
        panel2.add(tornaAllaHomeButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
